### PR TITLE
Continue devel of `*_gen` files and functions.

### PR DESCRIPTION
**Pull request by arturum1**

### CODE REVIEW

**Comment by jjts** [comment]
Why do you call super class methods?

Did you not inherit them?

**Comment by jjts** [comment]
We agreed to use the constructor, not _setup....

**Comment by arturum1** [comment]
> Why do you call super class methods?
> 
> Did you not inherit them?

Yes, the methods were inherited, but if we do not call the ones from the super class, then we would only be overriding the methods. Not extending their functionality.

**Comment by arturum1** [comment]
> We agreed to use the constructor, not _setup....

Yes, for now I am trying to make the system work as is, and afterwards perform the merge between _setup and __init__.
I can open an issue with  this so that we remember to do it.

**Pull request merged**
