### PR TITLE
The final working state with riffa and pcie periph

### PR DESCRIPTION
**Pull request by behzadjoudat**
the test code implemented is the channel tester of the riffa driver itself in the pcie periph dir which is to be chenged with the design of the user using the existing pios

### CODE REVIEW

**Comment by behzadjoudat** [comment]
the reason the check fails is that it tries to simulate all the .v files that are also in the riffa dir which it should not do that as they are there just to be included by some files. 
for example in the icarus failed test it indicates the missing vh file in the wrapper code which is included for the making of the fpga and not for the simulation.

also if you merge the iob-pcie pr then I will update this one with the updated status. you don't get notified about that repo I think.

**Comment by jjts** [comment]
I can't merge this because iob_pcie.v is full of serious mistakes.

It is pointless if something is working if customers will reject it. They will not take clunkiness.

**Comment by jjts** [comment]
I have fixed the private submodules and the checks are still failing 

A PR is only merged if checks pass 

Is your repo up to date with iob-soc / master? Do you know how to do that?

**Comment by behzadjoudat** [comment]
I have explained the reason the check fails in a comment before yours. but let me see what can I do to fix relevant errors.

**Comment by jjts** [comment]
you explained and I fixed it 

but there are more fails 

click  the red crosses of the failed tests

you should be able to figure out what went wrong a suggest a fix 

File .github/workflows/ci.yml specifies the tests that are run. 

You can also run the same tests on your terminal and figure it out 

First of all, can you figure out what each test does?

**Pull request closed without merging**
