### PR TITLE
Merge system branch

### PR DESCRIPTION
**Pull request by P-Miranda**
- merge system branch into build-lib branch
- update system branch scripts for build-lib workflow
- move custom makefile variables and targets from `info.mk` to `custom_setup.mk` and `custom.mk` makefile fragments (see IObundle/iob-lib#150)
- update LIB, CACHE and UART with latest `build-lib` branches
- pc-emul and firmware build targets working:
```Make
make setup
make -C iob_soc_V0.10 pc-emul-test
make -C iob_soc_V0.10 pc-emul-clean
make -C iob_soc_V0.10 fw-build
make -C iob_soc_V0.10 fw-clean
make clean
```

### CODE REVIEW

**Comment by jjts** [comment]
checks failed

**Review by arturum1 — APPROVED** [review]
Python changes look good.

**Comment by arturum1** [comment]
I was able to run the build targets mentioned.
The failed checks seem to be related to the interactive shell.

**Comment by P-Miranda** [comment]
> checks failed

Updated CI workflow to only run currently supported targets: `pc-emul` and `fw-build`

**Pull request merged**
