### PR TITLE
changes to run post synth simulation in skywater

### PR DESCRIPTION
**Pull request by microSharjeel**

### CODE REVIEW

**Comment by jjts** [comment]
I though memories need to be at the top-level but they are still buried in sram.v for example ? Why? Can place and route be done this way ?

**Comment by microSharjeel** [comment]
> I though memories need to be at the top-level but they are still buried in sram.v for example ? Why? Can place and route be done this way ?

Yes macro placement can be done at any level. What is required is to pass the hierarchical name to macro placement of OpenLane.

**Comment by microSharjeel** [comment]
Yes macro placement can be done at any level. What is required is to pass the hierarchical name to macro placement of OpenLane.

**Comment by jjts** [comment]
Is there any change to this PR to address the comments? Please close it.

**Pull request closed without merging**
